// Code generated by ent, DO NOT EDIT.

package note

const (
	// Label holds the string label denoting the note type in the database.
	Label = "note"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldMessage holds the string denoting the message field in the database.
	FieldMessage = "message"
	// FieldTag holds the string denoting the tag field in the database.
	FieldTag = "tag"
	// Table holds the table name of the note in the database.
	Table = "notes"
)

// Columns holds all SQL columns for note fields.
var Columns = []string{
	FieldID,
	FieldMessage,
	FieldTag,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// MessageValidator is a validator for the "message" field. It is called by the builders before save.
	MessageValidator func(string) error
)
